# management 프로젝트 생성
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-hotel-seoul-project
  namespace: argocd
spec:
  description: tenant-hotel-seoul project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'ResourceQuota'
  roles:
    - name: tenant-hotel-seoul
      description: tenant-hotel-seoul access to management project
      policies:
        - p, role:tenant-hotel-seoul, applications, *, tenant-hotel-seoul/*, allow
        - p, role:tenant-hotel-seoul, projects, *, tenant-hotel-seoul/*, allow
      groups:
        - tenant-hotel-seoul
---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: tenant-hotel-seoul
  template:
    metadata:
      name: '{{name}}-project'
    spec:
      project: '{{name}}-project'
      source:
        repoURL: 'https://github.com/saas-in-the-well/saas-kubernetes.git'
        targetRevision: develop
        path: kube/saas/application-plain
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

---
