# 권한설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    g, admin, role:admin
    g, hyeongwon, role:admin
    g, jaeho, role:admin
    g, seongjin, role:admin
  policy.default: ""

---

# management 프로젝트 생성
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: manage-project
  namespace: argocd
spec:
  description: Management project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'ResourceQuota'
  roles:
    - name: admin
      description: Full access to management project
      policies:
        - p, role:admin, applications, *, */*, allow
        - p, role:admin, projects, *, */*, allow
        - p, role:admin, clusters, *, *, allow
        - p, role:admin, repositories, *, *, allow
      groups:
        - admin

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-application
  namespace: argocd
spec:
  project: manage-project
  source:
    repoURL: 'https://github.com/saas-in-the-well/saas-kubernetes.git'
    targetRevision: develop
    path: kube/saas/control-plain
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: manage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true